server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: ${SECRET_KAFKA_HOST:localhost}:${SECRET_KAFKA_PORT:9092}
    consumer:
      group-id: "my-awesome-app"
  mail:
    host: smtp.gmail.com
    port: 587
    username: kookkook0199x@gmail.com
    password: ysnw rxjv mdbd urkt
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true




